### PR TITLE
Adding a skeleton for monitoring and tracing demo

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
@l0rd @slemeur wdyt?

**Comment by slemeur** [comment]
Good idea @ibuziuk !
Would it be possible to highlight a use case where the connectivity is causing some issues? Or when many workspaces are running concurrently and you need to operator/monitor the behavior of the platform?

**Comment by ibuziuk** [comment]
> Would it be possible to highlight a use case where the connectivity is causing some issues? 

do you mean internal networking issues? e.g. pods can not see one another by `service name` : `port` combo aka jwt-proxy can not redirect to the Theia IDE URL? or simply slow internet  connection?

> Or when many workspaces are running concurrently and you need to operator/monitor the behavior of the platform?

this is an interesting idea but I'm not sure we have enough test accounts to start sufficient amount of workspaces simultaneoulsy on prod (5 - 10 should be achivable though)

**Comment by ibuziuk** [comment]
@l0rd are you ok to merge the skeleton for tracing / monitoring demo?

**Review by l0rd — APPROVED** [review]

**Comment by l0rd** [comment]
@ibuziuk LGTM go ahead and merge

**Pull request merged**
